openapi: 3.0.3
info:
  title: ARD Reduction
  description: Reduce to ARD Level
  version: "0.8.0"
servers:
  - url: 'http://localhost:8080'
tags:
  - name: ARD Reduction
    description: Reduce GL String to ARD
paths:
  /redux:
    post:
      tags:
        - ARD Reduction
      operationId: api.redux_controller
      summary: Reduce to ARD
      description: |
        Given a GL String and a reduction method perform ARD Reduction
      requestBody:
        content:
          application/json:
            schema:
              properties:
                gl_string:
                  description: GL String
                  type: string
                  example: "A*01:01+A*01:01^B*08:ASXJP+B*07:02^C*02:02+C*07:HTGM^DPB1*28:01:01G+DPB1*296:01"
                reduction_method:
                  description: Reduction Method
                  type: string
                  enum:
                    - G
                    - lg
                    - lgx
                    - W
                    - exon
                    - U2
                  example: "lgx"
      responses:
        200:
          description: Reduction Result
          content:
            application/json:
              schema:
                type: object
                properties:
                  ard:
                    description: ARD reduced version of GL String
                    type: string
                    example: "A*01:01+A*01:01^B*07:02+B*08:01^C*02:02/C*02:10+C*07:01/C*07:150Q^DPB1*28:01+DPB1*28:01"
        400:
          description: Invalid GL String
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    description: Describes what went wrong
                    type: string
                    example: "Invalid HLA locus"
